// <auto-generated />
using ConsoleApp.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinT.Migrations
{
    [DbContext(typeof(MailContext))]
    [Migration("20180922055119_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("ConsoleApp.SQLite.InboxMail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("From");

                    b.Property<string>("Message");

                    b.Property<string>("PersonId");

                    b.Property<int>("Status");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("InboxMail");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.OutboxMail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("From");

                    b.Property<string>("Message");

                    b.Property<string>("PersonId");

                    b.Property<int>("Status");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("OutboxMail");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Sent");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.InboxMail", b =>
                {
                    b.HasOne("ConsoleApp.SQLite.Person")
                        .WithMany("Inbox")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.OutboxMail", b =>
                {
                    b.HasOne("ConsoleApp.SQLite.Person")
                        .WithMany("Outbox")
                        .HasForeignKey("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
